# 1. Update config.yaml

# This file is created to create the path where your data can be stored. this is done to make sure if you want
# to overwrite the existing data in the future then you need not want to make changes in the whole script
# you can easily do it by changing the above params 

artifacts_root: artifacts
data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/shivdattaredekar/TextSummarizer/raw/main/samsum.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

data_validation:
  root_dir : artifacts/data_validation
  STATUS_FILE : artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.json", "test.json", "validation.json"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv












