# 1. Update config.yaml

artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/shivdattaredekar/TextSummarizer/raw/main/samsum.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

# This file is created to create the path where your data can be stored. this is done to make sure if you want
# to overwrite the existing data in the future then you need not want to make changes in the whole script
# you can easily do it by changing the above params 











